lavalink.py

Also (at least, what I think is a) minor "improvement" to readability in socket retrying loop.

Clean up __init__ method signature

---

examples/music.py

typo in play of example cog

---

lavalink/Player.py

Adding ability to add tracks to the beginning of the queue.

Option for ADD NEXT

---

lavalink/WebSocket.py

Adding timeout on pong to detect unresponsive WS and close the connection. Fix* for AutoShardedBot when handling ConnectionClosed. Properly handling client disconnects on ConnectionClosed.
* `self._lavalink.bot.ws` was returning None on AutoShardedClient / AutoShardedBot

Detect unresponsive WS + Fix for AutoShardedBot

---

examples/music-v3.py

as 'isPlaylist' returns a KeyError

Update V3 example

---

lavalink/PlayerManager.py

I think it can be usefull to remove a player from the current players.

Removing a player from players

---

README.md
examples/music-v2.py
examples/music-v3.py
lavalink/AudioTrack.py
lavalink/Client.py
lavalink/Events.py
lavalink/PlayerManager.py
lavalink/Utils.py
lavalink/WebSocket.py

I've got a few improvements I wanted to share:
> Naming Conventions
*e.g. `lavalink.Utils.format_time`, h -> hours; s -> seconds*    
The goal of clean code should be human-readability. I don't think that variable names like h or s are really helpful so I changed them to be a bit more descriptive.  
> Fixing a few typos
*e.g `Websockets` -> `WebSockets`*  
Well, I think I shouldn't have to explain much for that point.  
> Using %-formatting isn't optimal and may cause errors
*Like it is used often in the debug logs, the method of string formatting through `%` isn't really good and may cause common errors.*  
So I replaced those through `.format()` which is newer and way more comfortable for formatting strings.
> Elaborating existing Docstrings and adding them where they were missing
*I …

Loads of changes. :)

---

examples/music-v2.py
examples/music-v3.py

Avoid an error in track_hook as `lavalink.Events.StatsUpdateEvent` doens't have an attribute `player`
Add `_previous`, `_playnow` and `_playat`
Minor fix in `_volume` docstring for v3

Fixing examples and adding new features according to AndyTempel last PR

---

lavalink/Client.py
lavalink/NodeManager.py
lavalink/PlayerManager.py
lavalink/WebSocket.py

Just some nicer imports with hate for prints

Nice imports

---

lavalink/NodeManager.py

After looking at my production logs I've noticed that i forgot to add brazil region to the `thirds` preset.

Forgot brazil region : ^)

---

lavalink/Client.py
lavalink/PlayerManager.py
lavalink/WebSocket.py
lavalink/__init__.py

- I've added more implicit things by removing every explicit things because according to someone implicit is OP.
Tests output:

Implicit is op

---

.travis.yml
examples/music-v2.py
examples/music-v3.py
lavalink/AudioTrack.py
lavalink/Client.py
lavalink/NodeManager.py
lavalink/PlayerManager.py
lavalink/WebSocket.py

Tests output: [link](https://paste.ubuntu.com/p/gVnDkd7myz/) 
- Added `set_gain`, `bulk_set_gain`, `reset_equalizer` to the `DefaultPlayer` for EQ support.
- Fixed WS connection handler and player hand-over on fail for compatibility with EQ.
- Thanks to this new PR template fixed a lot of single-quote errors.
- Added `.travis.yml` file for Travis CI support.

Lavalink EQ support & Travis CI for dev

---

lavalink/nodemanager.py

Speed things up (i guess)

---

lavalink/nodemanager.py
lavalink/websocket.py

Fixing websockets auto reconnect and small changes

---

lavalink/__init__.py
lavalink/client.py
lavalink/models.py
lavalink/playermanager.py
lavalink/websocket.py

I don't know how to revert

---

examples/music-v2.py
examples/music-v3.py
lavalink/AudioTrack.py
setup.py

Tests output: let's say that it's okay ?
The dev branch needs the same changes, maybe I'll (or someone else) open another PR for it.
List of breaking changes :

Minor changes to examples according to discord.py breaking changes

---

examples/music.py
lavalink/__init__.py
lavalink/client.py
lavalink/exceptions.py
lavalink/models.py
lavalink/node.py
lavalink/nodemanager.py
lavalink/playermanager.py
lavalink/websocket.py

Tests output: 
```
-- flake8 test --
OK
-- pylint test --
OK
```
- Fixed breaking changes bugs
- Updated incomplete documentation (never was reviewed)
- `lavalink.Client._event_hooks`, makes more sense than `lavalink.client._event_hooks`
- Exceptions from `lavalink.models` are moved to `lavalink.exceptions` and removed `NoPreviousTrack` due it not being used.

fixing my big fucky-wuckys owo

---

lavalink/__init__.py
lavalink/events.py
lavalink/models.py
lavalink/websocket.py

Tests output: 
```
-- flake8 test --
OK
-- pylint test --
OK
```
- `DefaultPlayer.add` can now take a `AudioTrack` too.
- `AudioTrack` is subscriptable, so can be used like `AudioTrack['author']`, just for convenience sake.
- Clearer `TrackStuckEvent` docstring.

Improvement Changes

---

lavalink/__init__.py
lavalink/models.py

Tests output: [link](https://mystb.in/izaqafafoq.bash) 
- I've added added set_repeat/shuffle to the default player instead of using weird methods like:
```py
not player.repeat
```
etc..

Add set_repeat/shuffle to defaultplayer

---

examples/music.py

Tests output: [link](https://put-your-link-to-your-output.here) 
- Removed the ``connect_to`` helper function and moved to the officially supported & documented ``discord.Guild`` method to leave/join a voice channel (``change_voice_state``)

Remove usage of internal functions

---

README.md
docs/index.rst
docs/quickstart.rst

This simply fixes the links since Fred changed username.
**Frederikam** ➡️ **freyacodes**

Fix new username to Lavalink repo

---

examples/music.py

Tests output: [link](http://hastebin.com/cafecopifi.lua) 
I've added a VoiceProtocol/VoiceClient implementation on the `examples/music.py` file which fixes the problem mentioned in #112. 
I am also aware there is already a similar fix with Merge Request  #114 but this change puts the part on the user implementation of the bot and results in not needing discord.py as a dependency for the project. Also this doesn't touch any internals of lavalink.py.
Also `run_tests.py` gives an flake8 error for a file that I didn't touch, so I marked that checkmark despite that, I hope that is alright.

Update example to use voice client

---

docs/lavalink.rst
lavalink/client.py
lavalink/models.py
lavalink/node.py

Adds support for getting the available plugins on a node. Refer to https://github.com/freyacodes/Lavalink/blob/dev/IMPLEMENTATION.md#get-list-of-plugins
This is currently only applicable to Lavalink dev version but will likely become relevant to master in the future.

Add plugin support
